/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "my_prog.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/types.h> 
#include <sys/socket.h>
#include <netinet/in.h>
#include <ctype.h>

void error(const char *msg)
{
    perror(msg);
    exit(1);
}

void
my_prog_1(char *host,int newsockfd,int sockfd)
{
	CLIENT *clnt;
	float  *result_1;
	arr  average_1_arg;
	max_min  *result_2;
	arr  maxmin_1_arg;
	ay  *result_3;
	a_prod_y  product_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MY_PROG, MY_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	

	
		
		
	int array[256] , length,n ,i,sum,choice;
	float ans,a;
      	int an[2];
	float farray[256];
     
 A: 
 	 n = write(newsockfd,"Enter your choice : \n1.Average\n2.max min\n3.Multiplication a*y\n 4.Exit\n",strlen("Enter your choice : \n1.Average\n2.max min\n3.Multiplication a *y\n 4.Exit\n"));        
   	  if (n < 0) error("ERROR writing to socket");
    	 read(newsockfd, &choice, sizeof(int));					//Read choice
     	printf("Client - Choice is : %d\n" , choice);	


	if (choice == 4)
		goto B;





     n = write(newsockfd,"Enter Length : ",strlen("Enter Length"));            
     if (n < 0) error("ERROR writing to socket");
     read(newsockfd, &length, sizeof(int));					
     printf("Client - Array length is : %d\n" , length);
	
     n = write(newsockfd,"Enter floating number  : ",strlen("Enter floating number"));              
     if (n < 0) error("ERROR writing to socket");
     read(newsockfd, &a, sizeof(float));
     

     n = write(newsockfd,"Enter Numbers : ",strlen("Enter Numbers"));              
     if (n < 0) error("ERROR writing to socket");
     read(newsockfd, &array,256 * sizeof(int));					
   
     
     
  
     
     
      switch(choice)
     {
     	case 1: // AVERAGE
		average_1_arg.y.y_len=length;
		average_1_arg.n=length;
		average_1_arg.y.y_val=(int *) malloc(256*sizeof(int));
		for (i=0; i<256; i++)
			average_1_arg.y.y_val[i]=array[i];
		result_1 = average_1(&average_1_arg, clnt);
		if (result_1 == (float *) NULL) 
		{
			clnt_perror (clnt, "call failed");
		}
		else
		{
			printf("\n");
			printf("Average of y[] == %.2f\n", *result_1);
			printf("\n");
			ans=*result_1;
			write(newsockfd , &ans , sizeof(float));
		}
		
     		break;
     	case 2: //MAX MIN
     			maxmin_1_arg.y.y_len=length;
			maxmin_1_arg.n=length;
			maxmin_1_arg.y.y_val=(int *) malloc(256 * sizeof(int));
			for(i=0;i<256;i++)
				maxmin_1_arg.y.y_val[i]=array[i];	
			result_2 = maxmin_1(&maxmin_1_arg, clnt);
			if (result_2 == (max_min *) NULL) 
			{
				clnt_perror (clnt, "call failed");
			}
			else
			{
				printf("\n");
				printf("Max of y[] == %d\n", result_2->max);
				printf("Min of y[] == %d\n", result_2->min);
				printf("\n");
				an[0]=result_2->max;
				an[1]=result_2->min;
				write(newsockfd , &an ,2 * sizeof(int));
		
				
			}
			
     		break;
     	case 3:  //a*y[]
 
     			product_1_arg.y.y_len=length;
			product_1_arg.n=length;
			product_1_arg.y.y_val=(int *) malloc(256*sizeof(int));
			
			for(i=0;i<n;i++)
				product_1_arg.y.y_val[i]=array[i];	
			product_1_arg.a=a;
			result_3 = product_1(&product_1_arg, clnt);
			if (result_3 == (ay *) NULL) 
			{
				clnt_perror (clnt, "call failed");
			}
			else
			{
				printf("\n");
				for(i=0; i<length; i++)
					printf("a*y[%d] == %.2f\n", i, result_3->ay.ay_val[i]);
				printf("\n");
				for(i=0; i<length; i++)
					farray[i]=result_3->ay.ay_val[i];
				write(newsockfd , &farray ,256 * sizeof(float));
			}
     		break;
     	
     	
     }
     
    
     if(choice != 4)
     	goto A;
    
   B:  close(newsockfd);
       close(sockfd);
			
			
		
	
						
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	int sockfd, newsockfd, portno;
     socklen_t clilen;
     char buffer[1024];
     struct sockaddr_in serv_addr, cli_addr;
     int n;
     if (argc < 2) {
         fprintf(stderr,"ERROR, no port provided\n");
         exit(1);
     }
     sockfd = socket(AF_INET, SOCK_STREAM, 0);
     if (sockfd < 0) 
        error("ERROR opening socket");
     bzero((char *) &serv_addr, sizeof(serv_addr));
     portno = atoi(argv[1]);
     serv_addr.sin_family = AF_INET;
     serv_addr.sin_addr.s_addr = INADDR_ANY;
     serv_addr.sin_port = htons(portno);
     if (bind(sockfd, (struct sockaddr *) &serv_addr,
              sizeof(serv_addr)) < 0) 
              error("ERROR on binding");
     listen(sockfd,5);
     clilen = sizeof(cli_addr);
   int pid;
while (1)
{
     newsockfd = accept(sockfd, 
                 (struct sockaddr *) &cli_addr, 
                 &clilen);

     if (newsockfd < 0) 
          error("ERROR on accept");
	host = "localhost";
	pid = fork();
         if (pid < 0) {
              error("ERROR in new process creation");
         }
         if (pid == 0) {
		my_prog_1 (host,newsockfd,sockfd);
	}
	else
	{
		close(newsockfd);
	}
}
exit (0);
}
