/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "my_prog.h"

float *
average_1_svc(arr *argp, struct svc_req *rqstp)
{
	static float  result;

	printf("connection to avg calculation\n");
	
	int sum=0;
	int i;

	for(i=0;i<argp->n;i++)
		sum+=argp->y.y_val[i];
		
	result=sum/argp->n;

	return &result;
}

max_min *
maxmin_1_svc(arr *argp, struct svc_req *rqstp)
{
	static max_min  result;

	printf("connection to max min calculation\n");

	int i;

	result.max=argp->y.y_val[0];
	
	for(i=0;i<argp->n;i++)
		if(argp->y.y_val[i]>result.max)
			result.max=argp->y.y_val[i];

	result.min=result.max;
			
	for(i=0;i<argp->n;i++)
		if(argp->y.y_val[i]<result.min)
			result.min=argp->y.y_val[i];
	return &result;
}

ay *
product_1_svc(a_prod_y *argp, struct svc_req *rqstp)
{
	static ay  result;
	printf("calculation of a*y \n");

	result.ay.ay_len=argp->n;
	result.ay.ay_val=(float *)malloc(argp->n*sizeof(float));
	
	int i;
	
	for(i=0;i<argp->n;i++)
		result.ay.ay_val[i]=argp->a*argp->y.y_val[i];


	return &result;
}
