/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MY_PROG_H_RPCGEN
#define _MY_PROG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct arr {
	struct {
		u_int y_len;
		int *y_val;
	} y;
	int n;
};
typedef struct arr arr;

struct max_min {
	int max;
	int min;
};
typedef struct max_min max_min;

struct a_prod_y {
	struct {
		u_int y_len;
		int *y_val;
	} y;
	int n;
	float a;
};
typedef struct a_prod_y a_prod_y;

struct ay {
	struct {
		u_int ay_len;
		float *ay_val;
	} ay;
};
typedef struct ay ay;

#define MY_PROG 0x23450001
#define MY_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define average 1
extern  float * average_1(arr *, CLIENT *);
extern  float * average_1_svc(arr *, struct svc_req *);
#define maxmin 2
extern  max_min * maxmin_1(arr *, CLIENT *);
extern  max_min * maxmin_1_svc(arr *, struct svc_req *);
#define product 3
extern  ay * product_1(a_prod_y *, CLIENT *);
extern  ay * product_1_svc(a_prod_y *, struct svc_req *);
extern int my_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define average 1
extern  float * average_1();
extern  float * average_1_svc();
#define maxmin 2
extern  max_min * maxmin_1();
extern  max_min * maxmin_1_svc();
#define product 3
extern  ay * product_1();
extern  ay * product_1_svc();
extern int my_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_arr (XDR *, arr*);
extern  bool_t xdr_max_min (XDR *, max_min*);
extern  bool_t xdr_a_prod_y (XDR *, a_prod_y*);
extern  bool_t xdr_ay (XDR *, ay*);

#else /* K&R C */
extern bool_t xdr_arr ();
extern bool_t xdr_max_min ();
extern bool_t xdr_a_prod_y ();
extern bool_t xdr_ay ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MY_PROG_H_RPCGEN */
