/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "my_prog.h"

bool_t
xdr_arr (XDR *xdrs, arr *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->y.y_val, (u_int *) &objp->y.y_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_max_min (XDR *xdrs, max_min *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->max))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_a_prod_y (XDR *xdrs, a_prod_y *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->y.y_val, (u_int *) &objp->y.y_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ay (XDR *xdrs, ay *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->ay.ay_val, (u_int *) &objp->ay.ay_len, ~0,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
